In [1]:
import sys
import os
import re

import pandas as pd
import sqlalchemy as sa

In [3]:
# Import scouting system packages
import server.scouting.output as out
from server.model.event import EventDal

In [4]:
# Get a database connection
connection_string = ('postgresql://irs1318:irs1318'
                     '@localhost:5432/scouting')
engine = sa.create_engine(connection_string)
conn = engine.connect()

In [5]:
# Set Current Event
current_event = "turing"
EventDal.set_current_event(current_event)

In [6]:
col_name= 'placeGears'
new_name= 'placeCubeSwitch'
table_name = 'public.tasks'

sql_update= sa.text("UPDATE" + table_name + "," +
                    "SET name =" + new_name + "," +
                    "WHERE name =" + col_name+ ";")

In [7]:
# Get Measures Dataframe
sql_measures = sa.text(
    "SELECT events.name AS event, matches.name AS match, levels.name AS level, dates.name AS date, "
    "teams.name AS team, alliances.name AS alliance, "
    "stations.name AS station, phases.name AS phase, actors.name AS actor, tasks.name AS task, "
    "measures.capability AS capability, measures.successes as successes, measures.attempts AS attempts, "
    "measures.cycle_times as cycle_times, measuretypes.name AS measuretype, reasons.name AS reason, "
    "attempts.name AS attempt "
    "FROM ((((((((((((measures FULL OUTER JOIN teams ON measures.team_id=teams.id) "
    "LEFT JOIN events ON measures.event_id=events.id) "
    "LEFT JOIN matches ON measures.match_id=matches.id) "
    "LEFT JOIN levels ON measures.level_id=levels.id) "
    "LEFT JOIN dates ON measures.date_id=dates.id) "
    "LEFT JOIN alliances ON measures.alliance_id=alliances.id) "
    "LEFT JOIN stations ON measures.station_id=stations.id) "
    "LEFT JOIN phases ON measures.phase_id=phases.id) "
    "LEFT JOIN actors ON measures.actor_id=actors.id) "
    "LEFT JOIN tasks ON measures.task_id=tasks.id) "
    "LEFT JOIN reasons ON measures.reason_id=reasons.id) "
    "LEFT JOIN measuretypes ON measures.measuretype_id=measuretypes.id) "
    "LEFT JOIN attempts ON measures.attempt_id=attempts.id "
    "WHERE events.name='" + current_event + "';")
measures = pd.read_sql(sql_measures, conn)
measures

,event,match,level,date,team,alliance,station,phase,actor,task,capability,successes,attempts,cycle_times,measuretype,reason,attempt
0,turing,001-q,qual,2017-04-20T08:30:00,1983,blue,2,auto,robot,placeGear,0,0,1,0,boolean,na,summary
1,turing,001-q,qual,2017-04-20T08:30:00,1983,blue,2,auto,robot,holdGear,0,1,1,0,boolean,na,summary
2,turing,003-q,qual,2017-04-20T08:46:00,948,red,2,auto,robot,moveBaseline,0,1,1,0,boolean,na,summary
3,turing,003-q,qual,2017-04-20T08:46:00,6431,red,3,auto,robot,moveBaseline,0,1,1,0,boolean,na,summary
4,turing,001-q,qual,2017-04-20T08:30:00,1983,blue,2,teleop,robot,placeGear,0,2,2,0,count,na,summary
5,turing,001-q,qual,2017-04-20T08:30:00,1983,blue,2,teleop,robot,pickupGearRetrival,0,1,1,0,boolean,na,summary
6,turing,002-q,qual,2017-04-20T08:38:00,2761,blue,2,auto,robot,holdGear,0,0,0,0,boolean,na,summary
7,turing,002-q,qual,2017-04-20T08:38:00,2761,blue,2,auto,robot,placeGear,0,0,0,0,boolean,na,summary
8,turing,002-q,qual,2017-04-20T08:38:00,2761,blue,2,teleop,robot,pickupGearRetrival,0,0,0,0,boolean,na,summary
9,turing,002-q,qual,2017-04-20T08:38:00,2990,blue,3,auto,robot,shootHighBoiler,0,0,0,0,count,na,summary
10,turing,001-q,qual,2017-04-20T08:30:00,1983,blue,2,auto,robot,startingLocation,2,0,0,0,enum,na,summary
11,turing,001-q,qual,2017-04-20T08:30:00,1983,blue,2,auto,robot,moveBaseline,0,1,1,0,boolean,na,summary
12,turing,003-q,qual,2017-04-20T08:46:00,4061,blue,2,auto,robot,startingLocation,2,0,0,0,enum,na,summary
13,turing,003-q,qual,2017-04-20T08:46:00,6431,red,3,auto,robot,startingLocation,2,0,0,0,enum,na,summary
14,turing,003-q,qual,2017-04-20T08:46:00,1523,blue,1,auto,robot,holdGear,0,1,1,0,boolean,na,summary
15,turing,003-q,qual,2017-04-20T08:46:00,948,red,2,auto,robot,startingLocation,3,0,0,0,enum,na,summary
16,turing,003-q,qual,2017-04-20T08:46:00,948,red,2,auto,robot,holdGear,0,1,1,0,boolean,na,summary
17,turing,003-q,qual,2017-04-20T08:46:00,6431,red,3,auto,robot,holdGear,0,1,1,0,boolean,na,summary
18,turing,003-q,qual,2017-04-20T08:46:00,4061,blue,2,auto,robot,placeGear,0,0,1,0,boolean,na,summary
19,turing,003-q,qual,2017-04-20T08:46:00,4061,blue,2,auto,robot,holdGear,0,1,1,0,boolean,na,summary
20,turing,003-q,qual,2017-04-20T08:46:00,4061,blue,2,auto,robot,moveBaseline,0,1,1,0,boolean,na,summary
21,turing,003-q,qual,2017-04-20T08:46:00,6554,blue,3,auto,robot,moveBaseline,0,0,1,0,boolean,na,summary
22,turing,003-q,qual,2017-04-20T08:46:00,2221,red,1,auto,robot,placeGear,0,0,0,0,boolean,na,summary
23,turing,003-q,qual,2017-04-20T08:46:00,2221,red,1,auto,robot,holdGear,0,1,1,0,boolean,na,summary
24,turing,003-q,qual,2017-04-20T08:46:00,948,red,2,auto,robot,placeGear,0,1,1,0,boolean,na,summary
25,turing,003-q,qual,2017-04-20T08:46:00,6554,blue,3,auto,robot,holdGear,0,1,1,0,boolean,na,summary
26,turing,003-q,qual,2017-04-20T08:46:00,4061,blue,2,teleop,robot,placeGear,0,3,3,0,count,na,summary
27,turing,003-q,qual,2017-04-20T08:46:00,948,red,2,teleop,robot,pickupGearRetrival,0,1,1,0,boolean,na,summary
28,turing,003-q,qual,2017-04-20T08:46:00,1523,blue,1,auto,robot,moveBaseline,0,1,1,0,boolean,na,summary
29,turing,003-q,qual,2017-04-20T08:46:00,4061,blue,2,teleop,robot,pickupGearRetrival,0,1,1,0,boolean,na,summary
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5449,turing,110-q,qual,2017-04-21T18:04:00,6413,red,3,finish,robot,climbRope,0,5,5,0,count,na,summary
5450,turing,110-q,qual,2017-04-21T18:04:00,3219,blue,1,finish,robot,pushTouchPad,0,1,1,0,boolean,na,summary
5451,turing,110-q,qual,2017-04-21T18:04:00,5908,red,2,finish,robot,pushTouchPad,0,1,1,0,boolean,na,summary
5452,turing,111-q,qual,2017-04-21T18:12:00,1165,red,3,teleop,robot,pickupGearFloor,0,0,0,0,boolean,na,summary
5453,turing,112-q,qual,2017-04-21T18:20:00,2102,red,2,auto,robot,placeGear,0,0,1,0,boolean,na,summary
5454,turing,111-q,qual,2017-04-21T18:12:00,3245,blue,2,teleop,robot,pickupGearRetrival,0,0,0,0,boolean,na,summary
5455,turing,111-q,qual,2017-04-21T18:12:00,16,blue,1,teleop,robot,pickupGearRetrival,0,0,0,0,boolean,na,summary
5456,turing,111-q,qual,2017-04-21T18:12:00,3245,blue,2,auto,robot,moveBaseline,0,1,1,0,boolean,na,summary
5457,turing,111-q,qual,2017-04-21T18:12:00,3245,blue,2,auto,robot,holdGear,0,1,1,0,boolean,na,summary
5458,turing,111-q,qual,2017-04-21T18:12:00,1983,red,1,auto,robot,holdGear,0,1,1,0,boolean,na,summary
5459,turing,112-q,qual,2017-04-21T18:20:00,3794,blue,1,teleop,robot,pickupGearRetrival,0,1,1,0,boolean,na,summary
5460,turing,111-q,qual,2017-04-21T18:12:00,4270,red,2,teleop,robot,pickupGearRetrival,0,1,1,0,boolean,na,summary
5461,turing,112-q,qual,2017-04-21T18:20:00,2102,red,2,teleop,robot,pickupGearRetrival,0,1,1,0,boolean,na,summary
5462,turing,112-q,qual,2017-04-21T18:20:00,3006,blue,3,teleop,robot,placeGear,0,1,2,0,count,na,summary
5463,turing,111-q,qual,2017-04-21T18:12:00,3245,blue,2,teleop,robot,placeGear,0,4,4,0,count,na,summary
5464,turing,111-q,qual,2017-04-21T18:12:00,5104,blue,3,teleop,robot,placeGear,0,4,5,0,count,na,summary
5465,turing,111-q,qual,2017-04-21T18:12:00,1983,red,1,finish,robot,disabled,0,1,1,0,boolean,na,summary
5466,turing,112-q,qual,2017-04-21T18:20:00,3794,blue,1,teleop,robot,placeGear,0,1,1,0,count,na,summary
5467,turing,112-q,qual,2017-04-21T18:20:00,399,red,3,finish,robot,climbRope,0,4,4,0,count,na,summary
5468,turing,112-q,qual,2017-04-21T18:20:00,3006,blue,3,teleop,robot,defendMovement,0,3,3,0,count,na,summary
5469,turing,112-q,qual,2017-04-21T18:20:00,3794,blue,1,teleop,robot,defendMovement,0,1,1,0,count,na,summary
5470,turing,112-q,qual,2017-04-21T18:20:00,108,red,1,finish,robot,climbRope,0,8,8,0,count,na,summary
5471,turing,112-q,qual,2017-04-21T18:20:00,3794,blue,1,finish,robot,disabled,0,0,0,0,boolean,na,summary
5472,turing,112-q,qual,2017-04-21T18:20:00,2102,red,2,teleop,robot,defendMovement,0,1,1,0,count,na,summary
5473,turing,112-q,qual,2017-04-21T18:20:00,108,red,1,finish,robot,pushTouchPad,0,1,1,0,boolean,na,summary
5474,turing,112-q,qual,2017-04-21T18:20:00,399,red,3,finish,robot,pushTouchPad,0,1,1,0,boolean,na,summary
5475,turing,112-q,qual,2017-04-21T18:20:00,1287,blue,2,teleop,robot,pickupGearRetrival,0,1,1,0,boolean,na,summary
5476,turing,112-q,qual,2017-04-21T18:20:00,3006,blue,3,finish,robot,pushTouchPad,0,1,1,0,boolean,na,summary
5477,turing,112-q,qual,2017-04-21T18:20:00,1287,blue,2,finish,robot,pushTouchPad,0,0,1,0,boolean,na,summary
5478,turing,112-q,qual,2017-04-21T18:20:00,399,red,3,teleop,robot,pickupGearFloor,0,1,1,0,boolean,na,summary